# location.msg

float64 w_ori_x
float64 w_ori_y
float64 w_ori_z
float64 w_ori_w

float64 w_line_vel_x
float64 w_line_vel_y
float64 w_line_vel_z

float64 w_line_acc_x
float64 w_line_acc_y
float64 w_line_acc_z

float64 w_ang_vel_x
float64 w_ang_vel_y
float64 w_ang_vel_z

float64 heading

float64 b_line_acc_vrf_x
float64 b_line_acc_vrf_y
float64 b_line_acc_vrf_z

float64 b_ang_vel_vrf_x
float64 b_ang_vel_vrf_y
float64 b_ang_vel_vrf_z

float64 euler_angles_x
float64 euler_angles_y
float64 euler_angles_z

float64 latitude  # Updated field name
float64 longitude

bool reliable

float64 rely_on_fastlio_distance
